In [82]:
#Source - https://www.kaggle.com/c/boston-housing

import torch
import torch.nn as nn
import numpy as np
import pandas as pd

In [83]:
dataset = '~/Downloads/Machine-learning/2022Practice/Boston_Housing/Boston.csv'
df = pd.read_csv(dataset)
df.head()

Unnamed: 0     crim    zn  indus  chas    nox     rm   age     dis  rad  \
0           1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1   
1           2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2   
2           3  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2   
3           4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3   
4           5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3   

   tax  ptratio   black  lstat  medv  
0  296     15.3  396.90   4.98  24.0  
1  242     17.8  396.90   9.14  21.6  
2  242     17.8  392.83   4.03  34.7  
3  222     18.7  394.63   2.94  33.4  
4  222     18.7  396.90   5.33  36.2

In [84]:
df = df.drop('Unnamed: 0', 1)
df_test = df.drop('medv', 1)
targets = df['medv']
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [85]:
df_test

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio   black  lstat  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [86]:
targets

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [87]:
train_inputs = df_test.iloc[:400]
target_inputs = df_test.iloc[400:]
train_outputs = targets.iloc[:400]
target_outputs = targets.iloc[400:]

In [88]:
train_inputs = torch.Tensor(train_inputs.values)
target_inputs = torch.Tensor(target_inputs.values)
train_outputs = torch.Tensor(train_outputs.values)
target_outputs = torch.Tensor(target_outputs.values)

In [89]:
test_inputs.dtype

torch.float32

In [90]:
target_outputs

tensor([ 5.6000,  7.2000, 12.1000,  8.3000,  8.5000,  5.0000, 11.9000, 27.9000,
        17.2000, 27.5000, 15.0000, 17.2000, 17.9000, 16.3000,  7.0000,  7.2000,
         7.5000, 10.4000,  8.8000,  8.4000, 16.7000, 14.2000, 20.8000, 13.4000,
        11.7000,  8.3000, 10.2000, 10.9000, 11.0000,  9.5000, 14.5000, 14.1000,
        16.1000, 14.3000, 11.7000, 13.4000,  9.6000,  8.7000,  8.4000, 12.8000,
        10.5000, 17.1000, 18.4000, 15.4000, 10.8000, 11.8000, 14.9000, 12.6000,
        14.1000, 13.0000, 13.4000, 15.2000, 16.1000, 17.8000, 14.9000, 14.1000,
        12.7000, 13.5000, 14.9000, 20.0000, 16.4000, 17.7000, 19.5000, 20.2000,
        21.4000, 19.9000, 19.0000, 19.1000, 19.1000, 20.1000, 19.9000, 19.6000,
        23.2000, 29.8000, 13.8000, 13.3000, 16.7000, 12.0000, 14.6000, 21.4000,
        23.0000, 23.7000, 25.0000, 21.8000, 20.6000, 21.2000, 19.1000, 20.6000,
        15.2000,  7.0000,  8.1000, 13.6000, 20.1000, 21.8000, 24.5000, 23.1000,
        19.7000, 18.3000, 21.2000, 17.50

In [92]:
#Define and setup the dataset using pytorch inbuilt functions

from torch.utils.data import TensorDataset

train_ds = TensorDataset(train_inputs, train_outputs)

#print(train_ds[0:3])

In [94]:
print(train_inputs.shape)
print(target_inputs.shape)
print(train_outputs.shape)
print(target_outputs.shape)

torch.Size([400, 13])
torch.Size([106, 13])
torch.Size([400])
torch.Size([106])


In [95]:
#Define and setup the DataLoader

from torch.utils.data import DataLoader

batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle = True)

for xb,yb in train_dl:
    print(xb)
    print(yb)
    break



tensor([[1.1108e+01, 0.0000e+00, 1.8100e+01, 0.0000e+00, 6.6800e-01, 4.9060e+00,
         1.0000e+02, 1.1742e+00, 2.4000e+01, 6.6600e+02, 2.0200e+01, 3.9690e+02,
         3.4770e+01],
        [1.3600e-02, 7.5000e+01, 4.0000e+00, 0.0000e+00, 4.1000e-01, 5.8880e+00,
         4.7600e+01, 7.3197e+00, 3.0000e+00, 4.6900e+02, 2.1100e+01, 3.9690e+02,
         1.4800e+01],
        [5.2018e+00, 0.0000e+00, 1.8100e+01, 1.0000e+00, 7.7000e-01, 6.1270e+00,
         8.3400e+01, 2.7227e+00, 2.4000e+01, 6.6600e+02, 2.0200e+01, 3.9543e+02,
         1.1480e+01],
        [1.3428e+00, 0.0000e+00, 1.9580e+01, 0.0000e+00, 6.0500e-01, 6.0660e+00,
         1.0000e+02, 1.7573e+00, 5.0000e+00, 4.0300e+02, 1.4700e+01, 3.5389e+02,
         6.4300e+00],
        [3.5480e-02, 8.0000e+01, 3.6400e+00, 0.0000e+00, 3.9200e-01, 5.8760e+00,
         1.9100e+01, 9.2203e+00, 1.0000e+00, 3.1500e+02, 1.6400e+01, 3.9518e+02,
         9.2500e+00]])
tensor([13.8000, 18.9000, 22.7000, 24.3000, 20.9000])


In [97]:
class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.linear1 = nn.Linear(13,50)
        self.act1 = nn.ReLU()
        self.linear2 = nn.Linear(50,10)
        self.act2 = nn.ReLU()
        self.Linear3 = nn.Linear(10,1)
        
    def forward(self, x):
        x = self.linear1(x)
        x = self.act1(x)
        x = self.linear2(x)
        x = self.act2(x)
        x = self.Linear3(x)
        return x

In [98]:
model = SimpleNet()
opt = torch.optim.SGD(model.parameters(), lr = 1e-5)
loss_fn = F.mse_loss



In [99]:
#Define Optimizer/Algorithm - SGD (GD) & Train the model

opt = torch.optim.SGD(model.parameters(), lr=1e-5)

def Fit(num_epochs, model, loss_fn, opt, train_dl):
    
    for epoch in range(num_epochs):
        
        for xb,yb in train_dl:
            
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
        
        if (epoch+1) % 10 ==0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))



In [100]:
Fit(200, model, loss_fn, opt, train_dl)

<ipython-input-99-e0efd1cf4564>:12: UserWarning: Using a target size (torch.Size([5])) that is different to the input size (torch.Size([5, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  loss = loss_fn(pred, yb)


Epoch [10/200], Loss: 5.7538
Epoch [20/200], Loss: 83.9292
Epoch [30/200], Loss: 140.8531
Epoch [40/200], Loss: 20.0558
Epoch [50/200], Loss: 57.7552
Epoch [60/200], Loss: 44.5492
Epoch [70/200], Loss: 159.2530
Epoch [80/200], Loss: 22.6874
Epoch [90/200], Loss: 128.4899
Epoch [100/200], Loss: 59.1582
Epoch [110/200], Loss: 42.3482
Epoch [120/200], Loss: 46.0161
Epoch [130/200], Loss: 183.0500
Epoch [140/200], Loss: 5.2911
Epoch [150/200], Loss: 23.7761
Epoch [160/200], Loss: 41.6357
Epoch [170/200], Loss: 15.2419
Epoch [180/200], Loss: 43.4800
Epoch [190/200], Loss: 52.1899
Epoch [200/200], Loss: 50.8675


In [101]:
print("targets are",target_outputs)
print("predictions are", model(train_outputs))

targets are tensor([ 5.6000,  7.2000, 12.1000,  8.3000,  8.5000,  5.0000, 11.9000, 27.9000,
        17.2000, 27.5000, 15.0000, 17.2000, 17.9000, 16.3000,  7.0000,  7.2000,
         7.5000, 10.4000,  8.8000,  8.4000, 16.7000, 14.2000, 20.8000, 13.4000,
        11.7000,  8.3000, 10.2000, 10.9000, 11.0000,  9.5000, 14.5000, 14.1000,
        16.1000, 14.3000, 11.7000, 13.4000,  9.6000,  8.7000,  8.4000, 12.8000,
        10.5000, 17.1000, 18.4000, 15.4000, 10.8000, 11.8000, 14.9000, 12.6000,
        14.1000, 13.0000, 13.4000, 15.2000, 16.1000, 17.8000, 14.9000, 14.1000,
        12.7000, 13.5000, 14.9000, 20.0000, 16.4000, 17.7000, 19.5000, 20.2000,
        21.4000, 19.9000, 19.0000, 19.1000, 19.1000, 20.1000, 19.9000, 19.6000,
        23.2000, 29.8000, 13.8000, 13.3000, 16.7000, 12.0000, 14.6000, 21.4000,
        23.0000, 23.7000, 25.0000, 21.8000, 20.6000, 21.2000, 19.1000, 20.6000,
        15.2000,  7.0000,  8.1000, 13.6000, 20.1000, 21.8000, 24.5000, 23.1000,
        19.7000, 18.3000, 21

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x400 and 13x50)