In [33]:
#Source - https://aakashns.medium.com/linear-regression-with-pytorch-3dde91d60b50
#Lets Understand the shit outta this

import numpy as np
import torch
import math

#Input (temp, rainfall, humidity)
inputs = np.array([[73,67,43],[91,88,64],[87,134,58],[102,43,37],[69,96,70]],dtype='float32')
targets = np.array([[56,70],[81,101],[119,133],[22,37],[103,119]],dtype='float32')

#Conver numpy array to tensor
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)


tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [34]:
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-1.1413,  0.0845,  0.4709],
        [-0.6962,  1.3375,  0.4698]], requires_grad=True)
tensor([0.2846, 0.5549], requires_grad=True)


In [35]:
#Define model and loss
def model(x):
    return x @ w.t() + b

def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [36]:
# Generate predictions
preds = model(inputs)
print("Original predictions", preds)

# Compare with targets
print("Targets are", targets)

# Compute loss
loss = mse(preds, targets)
print("original loss", loss)

tensor([[-57.1184,  59.5448],
        [-65.9981,  84.9663],
        [-60.3700, 146.4577],
        [-95.0694,   4.4351],
        [-37.3885, 113.8023]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
original loss tensor(10162.6963, grad_fn=<DivBackward0>)


In [38]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()


In [40]:
#Verify loss, predictions & Targets
preds = model(inputs)
loss = mse(preds, targets)
print(loss)
print("Predictions are", preds)
print("Targets are", targets)

tensor(20.0643, grad_fn=<DivBackward0>)
Predictions are tensor([[ 56.9624,  69.3855],
        [ 83.4601,  96.6939],
        [116.1698, 143.4883],
        [ 19.7595,  30.7673],
        [104.9295, 115.9765]], grad_fn=<AddBackward0>)
Targets are tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
