In [1]:
#Source - https://aakashns.medium.com/linear-regression-with-pytorch-3dde91d60b50
#Lets Understand the shit outta this

import numpy as np
import torch
import math

#Input (temp, rainfall, humidity)
inputs = np.array([[73,67,43],[91,88,64],[87,134,58],[102,43,37],[69,96,70]],dtype='float32')
targets = np.array([[56,70],[81,101],[119,133],[22,37],[103,119]],dtype='float32')

#Conver numpy array to tensor
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)


tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [2]:
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.8393, -0.4780, -0.2102],
        [-1.2156, -1.6832,  0.2304]], requires_grad=True)
tensor([ 0.2718, -3.5448], requires_grad=True)


In [3]:
#Define model and loss
def model(x):
    return x @ w.t() + b

def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [4]:
# Generate predictions
preds = model(inputs)
print("Original predictions", preds)

# Compare with targets
print("Targets are", targets)

# Compute loss
loss = mse(preds, targets)
print("original loss", loss)

Original predictions tensor([[-102.0617, -195.1502],
        [-131.6213, -247.5401],
        [-148.9906, -321.4879],
        [-113.6684, -191.3863],
        [-118.2419, -232.8814]], grad_fn=<AddBackward0>)
Targets are tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
original loss tensor(78368.9219, grad_fn=<DivBackward0>)


In [5]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()


In [6]:
#Verify loss, predictions & Targets
preds = model(inputs)
loss = mse(preds, targets)
print("Loss is", loss)
print("Predictions are", preds)
print("Targets are", targets)

tensor(126.1041, grad_fn=<DivBackward0>)
Predictions are tensor([[ 59.9237,  73.4079],
        [ 82.6187, 106.9663],
        [113.3226, 113.6462],
        [ 36.6952,  58.8803],
        [ 93.5807, 116.6356]], grad_fn=<AddBackward0>)
Targets are tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
