In [1]:
#Linear regression using PyTorch built-ins
#Source - https://aakashns.medium.com/linear-regression-with-pytorch-3dde91d60b50

import torch
import torch.nn as nn
import numpy as np

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

print(inputs)
print(inputs.shape)
print(targets.shape)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
torch.Size([15, 3])
torch.Size([15, 2])


In [51]:
#Define and setup the dataset using pytorch inbuilt functions

from torch.utils.data import TensorDataset

train_ds = TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [52]:
#Define and setup the DataLoader

from torch.utils.data import DataLoader

batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle = True)

for xb,yb in train_dl:
    print(xb)
    print(yb)
    break


tensor([[102.,  43.,  37.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 91.,  88.,  64.],
        [ 73.,  67.,  43.]])
tensor([[ 22.,  37.],
        [ 22.,  37.],
        [103., 119.],
        [ 81., 101.],
        [ 56.,  70.]])


In [53]:
#Define the model for weights and bias using in-built nn.Linear which does it automatically
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

# Parameters
list(model.parameters())

preds = model(inputs)
print(preds)

Parameter containing:
tensor([[0.0524, 0.0849, 0.0788],
        [0.3405, 0.0092, 0.3851]], requires_grad=True)
Parameter containing:
tensor([-0.3029, -0.5692], requires_grad=True)
tensor([[12.5988, 41.4617],
        [16.9791, 55.8703],
        [20.2012, 52.6207],
        [11.6099, 48.8055],
        [16.9770, 50.7630],
        [12.5988, 41.4617],
        [16.9791, 55.8703],
        [20.2012, 52.6207],
        [11.6099, 48.8055],
        [16.9770, 50.7630],
        [12.5988, 41.4617],
        [16.9791, 55.8703],
        [20.2012, 52.6207],
        [11.6099, 48.8055],
        [16.9770, 50.7630]], grad_fn=<AddmmBackward0>)


In [54]:
#Define Loss Function

import torch.nn.functional as F

loss_fn = F.mse_loss

loss = loss_fn(model(inputs), targets)
print(loss)


tensor(3735.9065, grad_fn=<MseLossBackward0>)


In [6]:
#Define Optimizer/Algorithm - SGD (GD) & Train the model

opt = torch.optim.SGD(model.parameters(), lr=1e-5)

def Fit(num_epochs, model, loss_fn, opt, train_dl):
    
    for epoch in range(num_epochs):
        
        for xb,yb in train_dl:
            
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
        
        if (epoch+1) % 10 ==0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))


In [7]:
Fit(200, model, loss_fn, opt, train_dl)

Epoch [10/200], Loss: 797.6295
Epoch [20/200], Loss: 366.1983
Epoch [30/200], Loss: 381.5139
Epoch [40/200], Loss: 233.3836
Epoch [50/200], Loss: 143.6060
Epoch [60/200], Loss: 80.8589
Epoch [70/200], Loss: 40.1372
Epoch [80/200], Loss: 46.5645
Epoch [90/200], Loss: 21.2242
Epoch [100/200], Loss: 16.3117
Epoch [110/200], Loss: 21.7140
Epoch [120/200], Loss: 24.0048
Epoch [130/200], Loss: 27.9846
Epoch [140/200], Loss: 6.1314
Epoch [150/200], Loss: 14.2049
Epoch [160/200], Loss: 15.8753
Epoch [170/200], Loss: 9.8398
Epoch [180/200], Loss: 5.3859
Epoch [190/200], Loss: 7.4496
Epoch [200/200], Loss: 10.0936


In [8]:
print("targets are",targets)
print("predictions are", model(inputs))

targets are tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
predictions are tensor([[ 57.7035,  70.5767],
        [ 80.2686,  99.1933],
        [122.3352, 136.0088],
        [ 23.5802,  38.6210],
        [ 97.1482, 115.5588],
        [ 57.7035,  70.5767],
        [ 80.2686,  99.1933],
        [122.3352, 136.0088],
        [ 23.5802,  38.6210],
        [ 97.1482, 115.5588],
        [ 57.7035,  70.5767],
        [ 80.2686,  99.1933],
        [122.3352, 136.0088],
        [ 23.5802,  38.6210],
        [ 97.1482, 115.5588]], grad_fn=<AddmmBackward0>)


In [9]:
#Predict for a new input of Temp, Humidity, Rainfall

model(torch.tensor([[75, 63, 44.0]]))

tensor([[53.7185, 67.3157]], grad_fn=<AddmmBackward0>)

In [55]:
class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.linear1 = nn.Linear(3,4)
        self.act1 = nn.ReLU()
        self.linear2 = nn.Linear(4,2)
        
    def forward(self, x):
        x = self.linear1(x)
        x = self.act1(x)
        x = self.linear2(x)
        return x

In [56]:
model = SimpleNet()
opt = torch.optim.SGD(model.parameters(), lr = 1e-5)
loss_fn = F.mse_loss

In [57]:
Fit(200, model, loss_fn, opt, train_dl)

Epoch [10/200], Loss: 284.5976
Epoch [20/200], Loss: 81.7314
Epoch [30/200], Loss: 43.0357
Epoch [40/200], Loss: 11.3160
Epoch [50/200], Loss: 15.3251
Epoch [60/200], Loss: 6.3139
Epoch [70/200], Loss: 9.7411
Epoch [80/200], Loss: 6.0658
Epoch [90/200], Loss: 2.7667
Epoch [100/200], Loss: 1.5073
Epoch [110/200], Loss: 4.8560
Epoch [120/200], Loss: 4.5899
Epoch [130/200], Loss: 5.5940
Epoch [140/200], Loss: 6.7128
Epoch [150/200], Loss: 3.8739
Epoch [160/200], Loss: 1.4876
Epoch [170/200], Loss: 3.1109
Epoch [180/200], Loss: 2.6977
Epoch [190/200], Loss: 2.2153
Epoch [200/200], Loss: 2.7616


In [58]:
print("targets are",targets)
print("predictions are", model(inputs))

targets are tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
predictions are tensor([[ 57.0656,  70.4623],
        [ 81.9819,  99.4725],
        [119.2536, 135.5388],
        [ 21.0546,  37.7418],
        [101.4552, 116.6130],
        [ 57.0656,  70.4623],
        [ 81.9819,  99.4725],
        [119.2536, 135.5388],
        [ 21.0546,  37.7418],
        [101.4552, 116.6130],
        [ 57.0656,  70.4623],
        [ 81.9819,  99.4725],
        [119.2536, 135.5388],
        [ 21.0546,  37.7418],
        [101.4552, 116.6130]], grad_fn=<AddmmBackward0>)
