In [1]:
import torch
import numpy as np

In [27]:
a=torch.ones(10)

In [28]:
a

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
a.size

<function Tensor.size>

In [30]:
a.shape

torch.Size([10])

In [31]:
a.dtype

torch.float32

In [32]:
some_list=np.arange(10, dtype=float)

In [33]:
print(some_list)
print(some_list.dtype)
print(some_list.shape)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64
(10,)


In [34]:
a[:]

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
b = torch.ones(3,4,5)

In [36]:
b

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [37]:
b_transpose =b.transpose(0,2)

In [39]:
b_transpose.shape

torch.Size([5, 4, 3])

In [48]:
c = torch.randn(2,3,4).int()

In [49]:
c

tensor([[[ 0,  0, -1,  0],
         [ 0, -1,  1,  0],
         [-1,  0,  0,  0]],

        [[ 0, -1,  0,  0],
         [ 1,  0,  0,  2],
         [-1,  0,  0,  0]]], dtype=torch.int32)

In [55]:
c_transpose = c.transpose()

TypeError: transpose() received an invalid combination of arguments - got (), but expected one of:
 * (int dim0, int dim1)
 * (name dim0, name dim1)


In [54]:
c_transpose

<function Tensor.transpose>

In [58]:
np_c=np.arange(24).reshape(2,3,4)
np_c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [59]:
np_c.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])