In [12]:
import torch.nn as nn
import torch.nn.functional as F
import torch
import numpy as np
from torch.utils.data import TensorDataset, DataLoader

#Batching is done for large dataset to divide into smaller batches
#Using batches is called Stochastic Gradient Descent
#Here input and target have couple of additional copies to simulate a large dataset

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

#Define dataset for batching
train_ds =TensorDataset(inputs,targets)
print(train_ds[0:3])

#Define data loader
batch_size = 5
train_dl = DataLoader(train_ds,batch_size,shuffle=True)
next(iter(train_dl))

#Definer model
model = nn.Linear(3,2)
#print(model.weight)
#print(model.bias)


#Define optimizer
opt =torch.optim.SGD(model.parameters(),lr=1e-5)

#Loss function
loss_fn = F.mse_loss

#Create a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            #Generate predictions
            pred = model(xb)
            loss = loss_fn(pred,yb)
            #Perform GD
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ',loss_fn(model(inputs),targets))
    
fit(100,model,loss_fn,opt)
preds = model(inputs)
print(preds)
print(targets)

(tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.]]))
Training loss:  tensor(9.2247, grad_fn=<MseLossBackward>)
tensor([[ 58.3890,  70.6679],
        [ 83.6794, 100.6527],
        [113.8263, 132.4219],
        [ 28.0944,  39.3670],
        [100.3180, 117.6754],
        [ 58.3890,  70.6679],
        [ 83.6794, 100.6527],
        [113.8263, 132.4219],
        [ 28.0944,  39.3670],
        [100.3180, 117.6754],
        [ 58.3890,  70.6679],
        [ 83.6794, 100.6527],
        [113.8263, 132.4219],
        [ 28.0944,  39.3670],
        [100.3180, 117.6754]], grad_fn=<AddmmBackward>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
   