In [34]:
# Code for Tensors intro from EdX tensors course

import torch
import numpy as np
import pandas as pd

a = torch.Tensor([1,2,3,4,5])

print("type of tensor:",a.type())
print("size of tensor",a.size())
print("datatype of tensor:",a.dtype)
print("Dimensions of tensor:", a.ndimension())
print("")


#numpy <-> Pytorch

np_array = np.array([0,1,2,3,4,5])
torch_tensor = torch.from_numpy(np_array)
print ("np_array:",np_array,"torch_tensor:",torch_tensor)
back_2_np_array = torch_tensor.numpy()
print("Torch_tensor to np_array:",back_2_np_array)
print("")

#pandas <-> Pytorch
pandas_series = pd.Series([0,1,2,3,4,5])
pd_2_torch = torch.from_numpy(pandas_series.values)
print("pandas series",pandas_series,"torch_tensor:", pd_2_torch)
print("")

print ("Indexing & slicing")

c = torch.Tensor([10,20,30,40])
print(c)
c[0] = 50
print(c)
d = c[2:5]
print(d)


#c = torch.zeros([3,3], dtype=torch.int32)
#print(c)

type of tensor: torch.FloatTensor
size of tensor torch.Size([5])
datatype of tensor: torch.float32
Dimensions of tensor: 1

np_array: [0 1 2 3 4 5] torch_tensor: tensor([0, 1, 2, 3, 4, 5])
Torch_tensor to np_array: [0 1 2 3 4 5]

pandas series 0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64 torch_tensor: tensor([0, 1, 2, 3, 4, 5])

Indexing & slicing
tensor([10., 20., 30., 40.])
tensor([50., 20., 30., 40.])
tensor([30., 40.])
